import type { Article } from "../types";
import { featured } from "./_helpers";

export const everydayArticles: Article[] = [
  {
    id: "art_0201",
    slug: "7-ways-ai-can-save-you-time-this-week",
    title: "7 Ways AI Can Save You Time This Week",
    subtitle: "Small, specific, and useful — no technical skill required.",
    excerpt: "Forget the grand promises. Here are seven ordinary tasks an AI assistant can genuinely make faster, starting this afternoon.",
    shortSummary: "Seven ordinary tasks AI can genuinely speed up.",
    category: "everyday-ai",
    tags: ["Productivity", "Beginners"],
    authorSlug: "priya-natarajan",
    status: "published",
    publishedAt: "2026-09-13T09:00:00Z",
    updatedAt: "2026-09-13T09:00:00Z",
    featuredImage: featured("seven-ways-save-time", "Seven light-blue ticks arranged on a deep navy field with generous space between them."),
    trending: true,
    popular: true,
    keyTakeaways: ["Start with tasks you already do, not new ones.", "Paste, ask, check. That is the whole method.", "Ten minutes saved a day adds up."],
    relatedArticles: ["how-to-use-chatgpt-to-organize-your-week", "how-ai-can-help-you-write-better-emails", "how-ai-can-help-you-plan-a-vacation"],
    tools: ["chatgpt", "claude", "gemini"],
    content: [
      { type: "paragraph", text: "The most useful thing about AI is not dramatic. It is the ten minutes it saves you on a task you were dreading. Here are seven of those, each tested by our editors in the last month." },
      { type: "list", style: "number", items: [
        "Summarize a long email thread before you reply.",
        "Turn a messy list of notes into a clean to-do list.",
        "Draft a polite message you have been putting off.",
        "Explain a confusing bill or letter in plain English.",
        "Plan three dinners from what is already in the refrigerator.",
        "Rewrite a paragraph to sound shorter and clearer.",
        "Prepare three questions to ask before a doctor's appointment.",
      ] },
      { type: "explains", term: "How do I “paste” a document into an assistant?", text: "Select the text (or take a photo of a paper letter), copy it, and paste it into the assistant's message box. Then type what you want: “Explain this in simple terms” or “What do I need to do by when?” Most assistants also accept photos and PDF files directly." },
      { type: "callout", title: "A habit worth building", text: "Whenever you get something confusing — a form, a policy change, a long email — paste it in and ask “What is this asking me to do?” It is the single most useful question we know." },
      { type: "bottomLine", text: "Choose two from this list. Do them this week. If they help, you have found your starting point." },
    ],
  },
  {
    id: "art_0202",
    slug: "how-ai-can-help-you-plan-a-vacation",
    title: "How AI Can Help You Plan a Vacation (Without Doing It For You)",
    subtitle: "An assistant will not book your flights. It will make the planning far less tiring.",
    excerpt: "From a rough idea to a day-by-day plan in an afternoon. Here is how one of our editors used an AI assistant to plan a two-week trip — and where she ignored it.",
    shortSummary: "How to use an AI assistant to plan a trip, step by step.",
    category: "everyday-ai",
    tags: ["Travel", "Planning"],
    authorSlug: "priya-natarajan",
    status: "published",
    publishedAt: "2026-09-11T09:00:00Z",
    updatedAt: "2026-09-11T09:00:00Z",
    featuredImage: featured("plan-a-vacation", "A gentle horizon line in light blue over layered navy, suggesting a coastline at dusk."),
    popular: true,
    keyTakeaways: ["Start with constraints: dates, budget, pace, who is coming.", "Ask for options, not a single plan.", "Always confirm hours, prices and bookings yourself."],
    relatedArticles: ["7-ways-ai-can-save-you-time-this-week", "how-to-use-chatgpt-to-organize-your-week", "how-to-use-ai-safely"],
    content: [
      { type: "paragraph", text: "Planning a trip used to mean twelve browser tabs and a headache. Our correspondent planned two weeks in the Pacific Northwest with an AI assistant doing the tedious parts. Here is what worked." },
      { type: "heading", level: 2, text: "Step 1: Give it your constraints" },
      { type: "paragraph", text: "The better your first message, the better everything after it. Include dates, budget, how much driving you will tolerate, whether children or grandparents are coming, and what you enjoy. One paragraph is enough." },
      { type: "heading", level: 2, text: "Step 2: Ask for three options, not one" },
      { type: "paragraph", text: "Ask for three different shapes of trip — a slow one, a busy one, a mixed one. Choosing between them is easier than editing a single plan." },
      { type: "heading", level: 2, text: "Step 3: Go day by day" },
      { type: "paragraph", text: "Once you have a shape, ask for a day-by-day plan. Then push back: “Day four is too much driving.” The assistant will adjust without complaint." },
      { type: "callout", tone: "important", title: "Where to stop trusting it", text: "Opening hours, prices, seasonal closures and booking details change constantly and assistants get them wrong. Use the plan as a draft, then confirm every practical detail on the official website." },
      { type: "bottomLine", text: "Let the assistant do the shaping and the drudgery. Keep the decisions, and the bookings, for yourself." },
    ],
  },
  {
    id: "art_0203",
    slug: "how-to-use-chatgpt-to-organize-your-week",
    title: "How to Use ChatGPT to Organize Your Week",
    subtitle: "A ten-minute Sunday routine that our editors have kept for months.",
    excerpt: "Dump everything on your mind into an assistant, ask three questions, and start Monday with a clear list. Here is the exact routine.",
    shortSummary: "A simple Sunday routine for organizing the week with ChatGPT.",
    category: "everyday-ai",
    tags: ["ChatGPT", "Productivity"],
    authorSlug: "priya-natarajan",
    status: "published",
    publishedAt: "2026-09-09T09:00:00Z",
    updatedAt: "2026-09-09T09:00:00Z",
    featuredImage: featured("organize-your-week", "A calm seven-column grid in navy tones with one column highlighted in light blue."),
    keyTakeaways: ["Brain-dump first, organize second.", "Ask the assistant to group and prioritize, not to decide.", "Keep the routine to ten minutes."],
    relatedArticles: ["7-ways-ai-can-save-you-time-this-week", "how-ai-can-help-you-write-better-emails"],
    tools: ["chatgpt"],
    content: [
      { type: "paragraph", text: "This is not a productivity system. It is a ten-minute conversation, once a week, that leaves you with a short list and a clearer head." },
      { type: "list", style: "number", items: [
        "Open a new conversation and type everything on your mind — appointments, errands, worries, ideas. Do not organize it.",
        "Ask: “Group these into categories and tell me which three matter most this week.”",
        "Ask: “Which of these could be done in under ten minutes?”",
        "Ask: “Write this as a simple list for Monday to Friday.”",
      ] },
      { type: "quote", text: "The value is not that the assistant is clever. It is that it makes me say everything out loud, and then hands it back in order.", cite: "Priya Natarajan" },
      { type: "toolRecommendation", toolSlug: "chatgpt", note: "Any assistant works for this routine; we use ChatGPT because the phone app makes the brain-dump easy to dictate." },
      { type: "bottomLine", text: "Ten minutes on Sunday. A shorter list on Monday. That is the whole thing." },
    ],
  },
  {
    id: "art_0204",
    slug: "how-ai-can-help-you-write-better-emails",
    title: "How AI Can Help You Write Better Emails",
    subtitle: "Shorter, kinder, clearer — and still in your own voice.",
    excerpt: "The most common use of AI in America is probably email. Here is how to use it well, and how to keep your messages from sounding like a machine wrote them.",
    shortSummary: "Use AI for emails without sounding like a robot.",
    category: "everyday-ai",
    tags: ["Writing", "Email"],
    authorSlug: "priya-natarajan",
    status: "published",
    publishedAt: "2026-09-07T09:00:00Z",
    updatedAt: "2026-09-07T09:00:00Z",
    featuredImage: featured("write-better-emails", "A single folded paper form in warm white resting on a deep navy surface."),
    popular: true,
    keyTakeaways: ["Write the rough version yourself; let AI tidy it.", "Ask for specific changes: shorter, warmer, clearer.", "Always read the result out loud before sending."],
    relatedArticles: ["7-ways-ai-can-save-you-time-this-week", "claude-vs-chatgpt-what-normal-people-need-to-know"],
    tools: ["claude", "chatgpt", "gemini"],
    content: [
      { type: "paragraph", text: "There is a right way and a wrong way to use AI for email. The wrong way is to ask it to write the whole thing; the result is polite, generic and faintly robotic. The right way is to write badly yourself, then ask for help." },
      { type: "heading", level: 2, text: "The method" },
      { type: "list", style: "number", items: ["Type what you want to say as quickly and messily as you like.", "Paste it in and ask: “Make this shorter and warmer, keep my voice.”", "Read the result out loud. Change anything that does not sound like you.", "Send."] },
      { type: "heading", level: 2, text: "Useful phrases to ask for" },
      { type: "list", style: "bullet", items: ["“Make this less apologetic.”", "“Cut this in half.”", "“Add a clear request at the end.”", "“Make it sound less formal.”"] },
      { type: "explains", term: "Why does AI writing sound the same?", text: "Assistants are trained on enormous amounts of text and tend to average toward the most common phrasing. That is why a fully AI-written email can feel generic. Starting from your own words keeps your rhythm and your personality in the message." },
      { type: "bottomLine", text: "Draft like a human, edit with a machine, and always read it once out loud." },
    ],
  },
];
