import type { Article } from "../types";
import { featured } from "./_helpers";

export const guideArticles: Article[] = [
  {
    id: "art_0301",
    slug: "you-dont-need-to-be-a-tech-expert-to-use-ai",
    title: "You Don't Need to Be a Tech Expert to Use AI",
    subtitle: "If you can write an email, you already have every skill this requires. A gentle, complete introduction.",
    excerpt: "The NUVORA beginner's guide. What AI assistants are, what they are not, and how to try one for the first time — written for people who have never opened one.",
    shortSummary: "The complete beginner's guide to AI assistants.",
    category: "guides",
    tags: ["Beginners", "Explainers"],
    authorSlug: "margaret-hale",
    status: "published",
    publishedAt: "2026-09-10T08:00:00Z",
    updatedAt: "2026-09-15T12:00:00Z",
    featuredImage: featured("no-tech-expert", "A single light-blue circle resting in a wide field of warm paper, framed by a thin navy border."),
    featured: true,
    popular: true,
    keyTakeaways: ["An AI assistant is a program you talk to in plain sentences.", "It is useful for explaining, drafting and organizing; it is not a search engine and not a person.", "Your first task should be small and real."],
    seoTitle: "How to Start Using AI: A Beginner's Guide for Normal People",
    relatedArticles: ["how-to-understand-ai-without-the-jargon", "7-ways-ai-can-save-you-time-this-week", "how-to-use-ai-safely"],
    tools: ["chatgpt", "claude"],
    content: [
      { type: "paragraph", text: "Here is a secret the technology industry does not advertise. Using an AI assistant requires no technical skill whatsoever. It requires the ability to write a sentence and the willingness to read one back. That is all." },
      { type: "heading", level: 2, text: "What an AI assistant is" },
      { type: "paragraph", text: "An AI assistant is a website or app where you type a request in ordinary English and receive a written reply. You can ask it to explain something, write something, organize something or help you think something through. The reply arrives in seconds." },
      { type: "explains", term: "What does “large language model” actually mean?", text: "A large language model is the engine inside an assistant. It has read an enormous amount of text and learned the patterns of how words follow one another. When you type, it predicts the most useful continuation. That is why it can write fluently — and why it can also be confidently wrong." },
      { type: "heading", level: 2, text: "What it is not" },
      { type: "list", style: "bullet", items: ["It is not a person, and it does not remember you between sessions unless you turn that on.", "It is not a search engine. It may not know about recent events unless it is connected to the web.", "It is not always right. Treat it like a knowledgeable friend, not an encyclopedia."] },
      { type: "heading", level: 2, text: "Your first ten minutes" },
      { type: "list", style: "number", items: ["Open ChatGPT or Claude in your web browser. Create a free account.", "Find a real thing you need help with — a letter, a recipe, a confusing bill.", "Type it in, in your own words. Do not worry about phrasing.", "Read the reply. Ask a follow-up. Ask it to explain more simply.", "Close it. You have now used AI."] },
      { type: "quote", text: "The best first question is not clever. It is something you were going to have to deal with anyway.", cite: "Margaret Hale" },
      { type: "whyItMatters", text: "AI is arriving in the tools you already use. A little familiarity now means you will meet it with confidence rather than anxiety." },
      { type: "bottomLine", text: "You already have the skills. The only thing left is to try it once, with something real." },
      { type: "faq", items: [
        { question: "Is it safe to sign up?", answer: "Yes, with the same care you would use for any online account. Use a strong password and avoid sharing sensitive personal information in conversations." },
        { question: "Which one should I try first?", answer: "Either ChatGPT or Claude. Both are free to start and both are gentle with beginners." },
        { question: "What if I ask something silly?", answer: "There are no silly questions. The assistant will not judge you, and nobody is watching." },
      ] },
    ],
  },
  {
    id: "art_0302",
    slug: "how-to-understand-ai-without-the-jargon",
    title: "How to Understand AI Without the Jargon",
    subtitle: "Twelve words you keep hearing, explained in one plain sentence each.",
    excerpt: "Model, prompt, token, agent, hallucination. The vocabulary of AI is a barrier for many people. Here it is, translated.",
    shortSummary: "The twelve AI words you keep hearing, in plain English.",
    category: "guides",
    tags: ["Explainers", "Beginners", "Glossary"],
    authorSlug: "margaret-hale",
    status: "published",
    publishedAt: "2026-09-04T08:00:00Z",
    updatedAt: "2026-09-04T08:00:00Z",
    featuredImage: featured("without-the-jargon", "Rows of small navy typographic marks on paper with one word-length block picked out in light blue."),
    popular: true,
    keyTakeaways: ["Most AI jargon describes simple ideas.", "You can understand the news without learning the math.", "A dozen words cover almost everything you will hear."],
    relatedArticles: ["you-dont-need-to-be-a-tech-expert-to-use-ai", "ai-agents-are-coming-heres-what-that-means"],
    content: [
      { type: "paragraph", text: "The technology industry loves vocabulary. Most of it describes ideas that are simple once someone explains them properly. Here are the words you will hear most, translated." },
      { type: "explains", term: "Model", text: "The trained program at the heart of an AI tool. When a company releases a “new model,” it means a new version of the engine." },
      { type: "explains", term: "Prompt", text: "Whatever you type to the assistant. A question, an instruction, a pasted document." },
      { type: "explains", term: "Hallucination", text: "When an assistant states something false with confidence. It is not lying; it is pattern-matching without checking. Always verify important facts." },
      { type: "explains", term: "Agent", text: "An assistant that can take actions — fill forms, browse websites — rather than only writing text." },
      { type: "explains", term: "Token", text: "A small chunk of text, roughly three-quarters of a word. Usage limits and prices are often counted in tokens." },
      { type: "explains", term: "Training", text: "The process of showing a model enormous amounts of text so that it learns patterns. It happens before you use the tool, not while you use it." },
      { type: "bottomLine", text: "When a headline confuses you, look for one of these words. Nine times out of ten, that is the whole mystery." },
    ],
  },
  {
    id: "art_0303",
    slug: "how-to-use-ai-safely",
    title: "How to Use AI Safely: A Practical Guide for Normal People",
    subtitle: "Privacy, scams and mistakes — the habits that keep you safe without making you paranoid.",
    excerpt: "You do not need to fear AI. You do need a few sensible habits. Here they are, in order of importance.",
    shortSummary: "The practical habits that keep you safe when using AI.",
    category: "guides",
    tags: ["Safety", "Privacy", "Scams"],
    authorSlug: "margaret-hale",
    status: "published",
    publishedAt: "2026-08-30T08:00:00Z",
    updatedAt: "2026-09-12T15:30:00Z",
    featuredImage: featured("use-ai-safely", "Concentric rings in navy with a small light-blue centre, suggesting protection and focus."),
    popular: true,
    keyTakeaways: ["Never paste passwords, account numbers or medical records.", "Verify any fact that matters before acting on it.", "Be suspicious of any message, voice or video that asks for money — AI makes fakes easy."],
    relatedArticles: ["you-dont-need-to-be-a-tech-expert-to-use-ai", "ai-agents-are-coming-heres-what-that-means", "how-to-compare-ai-tools"],
    content: [
      { type: "paragraph", text: "Safety with AI comes down to three areas: what you put in, what you take out, and what other people can do with the same tools. Each has one or two habits worth adopting." },
      { type: "heading", level: 2, text: "What you put in" },
      { type: "paragraph", text: "Treat an assistant like a helpful stranger. Do not share passwords, account numbers, Social Security numbers or private medical details. Check the privacy settings once and turn off the option to use your conversations for training if you prefer." },
      { type: "heading", level: 2, text: "What you take out" },
      { type: "paragraph", text: "Assistants can be wrong. For anything that matters — a medication, a legal deadline, a tax rule — confirm the answer with a reliable source before acting on it." },
      { type: "heading", level: 2, text: "What others can do" },
      { type: "paragraph", text: "The same tools that write your emails can fake a voice or a video. If a call, message or video asks you for money or personal information urgently, stop. Hang up and call the person back on a number you already have." },
      { type: "callout", tone: "important", title: "The one habit that prevents most scams", text: "Agree on a family password — a word only your close family knows. If someone claiming to be a relative calls in distress, ask for it." },
      { type: "bottomLine", text: "Keep private things private, check what matters, and treat urgency as a warning sign. These three habits cover almost everything." },
      { type: "faq", items: [
        { question: "Can an assistant see my other apps?", answer: "Only if you grant it access. Standard assistants see only what you type or paste into them." },
        { question: "Is it safe to upload a photo of a letter?", answer: "Generally yes, but cover account numbers first. Most tools let you delete conversations afterward." },
      ] },
    ],
  },
];
