import type { Article } from "../types";
import { featured } from "./_helpers";

export const newsArticles: Article[] = [
  {
    id: "art_0001",
    slug: "ai-just-changed-again-heres-what-actually-matters",
    title: "AI Just Changed Again. Here's What Actually Matters.",
    subtitle:
      "A week of major announcements left most people confused. We read everything, so you only need to understand three things.",
    excerpt:
      "Three big AI companies shipped major updates in the same week. Most of it is noise. Here is the small part that will actually touch your life.",
    shortSummary: "Three announcements, one week, and only three things worth understanding.",
    category: "news",
    tags: ["ChatGPT", "Claude", "Gemini", "Explainers"],
    authorSlug: "margaret-hale",
    status: "published",
    publishedAt: "2026-09-18T06:00:00Z",
    updatedAt: "2026-09-18T10:30:00Z",
    featuredImage: featured(
      "ai-just-changed-again",
      "A calm, layered composition of navy planes with a single light-blue arc, suggesting a shift in direction.",
      "This week's changes are less about new abilities and more about where AI shows up.",
    ),
    featured: true,
    trending: true,
    popular: true,
    breaking: true,
    keyTakeaways: [
      "The assistants you already use got quieter and more useful, not louder.",
      "AI is moving into email, documents and phones — you will meet it whether you seek it out or not.",
      "None of the announcements change the basic advice: try one tool, for one real task, this week.",
    ],
    socialSummary: "Three AI announcements in one week. Only three things matter. NUVORA explains.",
    socialCaptions: {
      instagram: "AI changed again this week. Here's the short version, in plain English. Link in bio.",
      x: "AI just changed again. Here's what actually matters — in three points, no jargon.",
      facebook: "Confused by this week's AI news? You're not alone. We read everything so you don't have to.",
    },
    hashtags: ["#AI", "#AIforNormalPeople", "#NUVORA", "#Technology"],
    seoTitle: "AI Just Changed Again: What Actually Matters This Week",
    seoDescription:
      "Three AI companies shipped major updates in one week. NUVORA explains the three things that actually matter for normal people.",
    relatedArticles: [
      "chatgpt-has-a-new-feature-heres-why-it-actually-matters",
      "ai-agents-are-coming-heres-what-that-means",
      "you-dont-need-to-be-a-tech-expert-to-use-ai",
    ],
    tools: ["chatgpt", "claude", "gemini"],
    content: [
      {
        type: "paragraph",
        text: "If you felt a little lost this week, that is a reasonable response. In the space of four days, the three companies whose assistants most Americans have actually used all announced significant changes. The headlines were breathless. The press releases were long. And most of what was in them will never touch your life.",
      },
      {
        type: "paragraph",
        text: "So we did what we always do at NUVORA: we read all of it, tried what we could, and asked a simple question about each announcement. Will a normal person notice this? For most of it, the honest answer is no. For three things, the answer is yes.",
      },
      { type: "heading", level: 2, text: "1. The assistants are getting quieter" },
      {
        type: "paragraph",
        text: "The most important change is the least dramatic. All three assistants now do more of their work without being asked. Open a long email thread and a summary is already waiting. Paste a confusing letter from your insurer and the assistant offers to explain it before you have typed a word.",
      },
      {
        type: "paragraph",
        text: "This matters because the biggest barrier to using AI was never ability. It was the blank box. Most people did not know what to type. The tools are now meeting you where you already are, with suggestions instead of an empty prompt.",
      },
      {
        type: "explains",
        term: "What does “assistant” actually mean here?",
        text: "When we say AI assistant, we mean a program you can talk to in ordinary sentences — ChatGPT, Claude, Gemini and a few others. You type or speak a request, and it writes back. It is not a person, it does not know you, and it can be wrong. But for explaining, drafting and organizing, it is genuinely useful.",
      },
      { type: "heading", level: 2, text: "2. AI is moving into the apps you already own" },
      {
        type: "paragraph",
        text: "The second change is about location. Until recently, using AI meant going to a website. Now it is inside Gmail, inside Word, inside the Settings app on your phone. You will encounter it whether or not you go looking.",
      },
      {
        type: "list",
        style: "bullet",
        items: [
          "Email: summaries of long threads and suggested replies.",
          "Documents: a rewrite button next to the spell-checker.",
          "Phones: a single button that can explain what is on your screen.",
        ],
      },
      {
        type: "whyItMatters",
        text: "For the first time, the question is no longer “should I try AI?” It is “how do I want to handle the AI that is already in my email?” That is a different, more practical question — and a more comfortable one.",
      },
      { type: "heading", level: 2, text: "3. The advice has not changed" },
      {
        type: "paragraph",
        text: "Here is what we find reassuring. None of this week's announcements change the advice we would give a friend. Pick one assistant. Use it for one real task — a letter, a trip, a recipe, a form. See whether it helps. That is still the whole strategy, and it is still a good one.",
      },
      {
        type: "quote",
        text: "The people who get the most from AI are not the ones who follow every announcement. They are the ones who use it for one boring thing, every week.",
        cite: "Margaret Hale, Editor in Chief",
      },
      {
        type: "callout",
        title: "A note on what we did not cover",
        text: "Several announcements this week were aimed at software developers and large companies. We have left them out on purpose. If one of them starts to affect ordinary users, we will explain it then.",
      },
      {
        type: "bottomLine",
        text: "AI got quieter, closer and slightly more helpful this week. You do not need to do anything about it — but if you have been waiting for a good moment to try an assistant, this is a very reasonable one.",
      },
      {
        type: "faq",
        items: [
          { question: "Do I need to pay for any of this?", answer: "No. Every change we describe here is available in the free versions, sometimes with usage limits." },
          { question: "Will these features be turned on automatically?", answer: "Some will. In most apps you can switch them off in Settings, and we will publish a short guide on how." },
          { question: "Which assistant should I try first?", answer: "Whichever is already in the tools you use. If you use Gmail, try Gemini. If you use Microsoft Office, try Copilot. Otherwise, ChatGPT or Claude are both good starting points." },
        ],
      },
    ],
  },
  {
    id: "art_0002",
    slug: "chatgpt-has-a-new-feature-heres-why-it-actually-matters",
    title: "ChatGPT Has a New Feature. Here's Why It Actually Matters.",
    subtitle: "Most new features are for power users. This one is for everyone who has ever stared at an empty box.",
    excerpt: "ChatGPT now suggests what you might want to do before you type. It sounds small. For first-time users, it is the biggest change in years.",
    shortSummary: "ChatGPT's new suggestions fix the blank-box problem.",
    category: "news",
    tags: ["ChatGPT", "OpenAI"],
    authorSlug: "daniel-reyes",
    status: "published",
    publishedAt: "2026-09-17T12:00:00Z",
    updatedAt: "2026-09-17T18:45:00Z",
    featuredImage: featured("chatgpt-new-feature", "A warm paper field with a soft navy rectangle and a light-blue cursor mark, suggesting a text box waiting for input."),
    trending: true,
    popular: true,
    keyTakeaways: ["The empty prompt box was the biggest barrier for new users.", "Suggested starting points make the first five minutes far easier.", "The feature is free and on by default."],
    relatedArticles: ["ai-just-changed-again-heres-what-actually-matters", "how-to-use-chatgpt-to-organize-your-week", "the-5-ai-tools-worth-knowing-this-week"],
    tools: ["chatgpt"],
    content: [
      { type: "paragraph", text: "Ask people who tried ChatGPT once and never went back why they stopped, and you hear the same thing. They opened it, saw an empty box, and did not know what to type. They typed something small, got a fine answer, and closed the tab." },
      { type: "paragraph", text: "The new version addresses that directly. When you open ChatGPT, it now shows a handful of starting points based on what you have done before — “draft a reply to this email,” “explain this document,” “plan three dinners.” Choose one and you are working within seconds." },
      { type: "explains", term: "What is a prompt?", text: "A prompt is simply what you type to an AI assistant. It can be a question, an instruction, or a pasted document with a request attached. Good prompts are specific about what you want and who it is for — but you do not need special phrasing." },
      { type: "heading", level: 2, text: "Why this is bigger than it looks" },
      { type: "paragraph", text: "In our testing with readers new to AI, the difference was immediate. People who were previously hesitant chose a suggestion, saw a useful result, and then asked a follow-up of their own. The suggestions act as training wheels that come off on their own." },
      { type: "whyItMatters", text: "The hardest part of AI was never the technology. It was knowing where to begin. A feature that solves that for millions of people matters more than another benchmark score." },
      { type: "toolRecommendation", toolSlug: "chatgpt", note: "The free version includes the new suggestions. There is no need to pay to try them." },
      { type: "bottomLine", text: "If you tried ChatGPT before and drifted away, this is a good reason to open it again." },
    ],
  },
  {
    id: "art_0003",
    slug: "ai-agents-are-coming-heres-what-that-means",
    title: "AI Agents Are Coming. Here's What That Means.",
    subtitle: "The next wave of AI does not just answer questions — it does things. We explain what an “agent” is, what it can do today, and what to watch for.",
    excerpt: "You will hear the word “agent” a lot this year. Here is what it means in plain English, what agents can actually do today, and why a healthy caution is sensible.",
    shortSummary: "What an AI agent is, and what it can and cannot do today.",
    category: "news",
    tags: ["AI Agents", "Explainers", "Safety"],
    authorSlug: "margaret-hale",
    status: "published",
    publishedAt: "2026-09-15T09:00:00Z",
    updatedAt: "2026-09-16T08:10:00Z",
    featuredImage: featured("ai-agents-are-coming", "A sequence of connected navy blocks stepping across a paper background, suggesting a series of actions."),
    featured: true,
    popular: true,
    keyTakeaways: ["An agent is an AI that can take actions, not just write text.", "Today's agents handle simple, bounded tasks — booking, filling forms, comparing options.", "Always review before an agent spends money or sends messages on your behalf."],
    relatedArticles: ["ai-just-changed-again-heres-what-actually-matters", "how-to-use-ai-safely", "what-ai-means-for-your-job-a-calm-guide"],
    content: [
      { type: "paragraph", text: "For the past few years, using AI has meant asking a question and reading an answer. That is changing. The newest tools can take the answer and act on it — filling in a form, comparing prices across three websites, or moving a meeting on your calendar." },
      { type: "explains", term: "What is an “AI agent”?", text: "An agent is an AI assistant that can take steps on your behalf, usually inside a web browser or app. Instead of telling you how to book a table, it books the table. Think of it as an assistant with hands, not just a voice." },
      { type: "heading", level: 2, text: "What agents can actually do today" },
      { type: "list", style: "bullet", items: ["Fill out repetitive forms using information you provide.", "Compare a product across several stores and summarize the differences.", "Draft, then send, routine messages after you approve them.", "Reorganize a calendar around a change."] },
      { type: "paragraph", text: "Notice what these have in common. They are bounded, they are checkable, and a mistake is easy to undo. That is where agents work well right now." },
      { type: "heading", level: 2, text: "What to be careful about" },
      { type: "paragraph", text: "Agents can make the same mistakes as any assistant — misreading a page, choosing the wrong option — but now those mistakes can have consequences. The sensible habit is simple: an agent proposes, you approve. Never give one the ability to spend money or send messages without a review step." },
      { type: "callout", tone: "important", title: "Our standing advice", text: "Treat an AI agent like a new assistant on their first week. Give it small tasks, check its work, and expand its responsibilities only as it earns them." },
      { type: "bottomLine", text: "Agents are real, useful for small tasks, and not yet something to hand your credit card. That balance will shift, and we will tell you when it does." },
    ],
  },
  {
    id: "art_0004",
    slug: "three-announcements-one-morning-what-to-know",
    title: "Three AI Announcements in One Morning: What to Know Right Now",
    subtitle: "A quick, developing summary of this morning's news. We will update this story as we learn more.",
    excerpt: "OpenAI, Google and Anthropic all published updates before 9 a.m. Eastern. Here is the short version while our full explainer is in progress.",
    shortSummary: "A developing story: three morning announcements, summarized.",
    category: "news",
    tags: ["Developing", "ChatGPT", "Gemini", "Claude"],
    authorSlug: "nuvora-staff",
    status: "published",
    publishedAt: "2026-09-18T13:15:00Z",
    updatedAt: "2026-09-18T14:05:00Z",
    featuredImage: featured("three-announcements", "Three vertical navy bars of different heights on a paper background."),
    breaking: true,
    trending: true,
    relatedArticles: ["ai-just-changed-again-heres-what-actually-matters"],
    content: [
      { type: "paragraph", text: "This is a developing story. Our editors are reading the announcements now and will replace this summary with a full explainer later today." },
      { type: "list", style: "bullet", items: ["OpenAI announced changes to how ChatGPT suggests tasks.", "Google expanded Gemini features inside Gmail for more users.", "Anthropic published an update to Claude's document handling."] },
      { type: "callout", title: "What we know so far", text: "None of these changes require action from readers. All are arriving in free versions over the coming weeks." },
    ],
  },
];
