import type { Article } from "../types";
import { featured } from "./_helpers";

export const reviewArticles: Article[] = [
  {
    id: "art_0501",
    slug: "perplexity-review-the-search-engine-that-answers",
    title: "Perplexity Review: The Search Engine That Answers Back",
    subtitle: "We used it instead of Google for a month. Here is what we missed, and what we did not.",
    excerpt: "Perplexity replaces ten blue links with one answer and a list of sources. After a month, our tools editor has a clear view of who it suits.",
    shortSummary: "A month with Perplexity instead of Google.",
    category: "reviews",
    tags: ["Perplexity", "Search", "Reviews"],
    authorSlug: "daniel-reyes",
    status: "published",
    publishedAt: "2026-09-08T10:00:00Z",
    updatedAt: "2026-09-08T10:00:00Z",
    featuredImage: featured("perplexity-review", "A single light-blue line leading to a small navy square on paper, suggesting a question arriving at an answer."),
    popular: true,
    keyTakeaways: ["Excellent for research and purchases.", "Sources are shown — but still need a glance.", "Not a replacement for maps, shopping or local searches."],
    relatedArticles: ["the-5-ai-tools-worth-knowing-this-week", "how-to-compare-ai-tools"],
    tools: ["perplexity"],
    affiliateLinks: ["perplexity-pro"],
    content: [
      { type: "paragraph", text: "Editorial placeholder: this review structure is ready for a full hands-on report. The sections below reflect NUVORA's review format — what it is, who it is for, what we liked, what we did not, and a verdict." },
      { type: "heading", level: 2, text: "What it is" },
      { type: "paragraph", text: "Perplexity is an AI search engine. You ask a question in plain English; it reads relevant web pages and writes a short answer with numbered citations." },
      { type: "heading", level: 2, text: "What we liked" },
      { type: "list", style: "bullet", items: ["Clear answers for research questions", "Sources you can click and check", "No advertising clutter"] },
      { type: "heading", level: 2, text: "What we did not" },
      { type: "list", style: "bullet", items: ["Occasionally cites a weak source", "Less useful for local and shopping queries"] },
      { type: "toolRecommendation", toolSlug: "perplexity", note: "Free tier is enough to decide whether it suits you." },
      { type: "bottomLine", text: "Verdict placeholder — the tools desk assigns a final verdict after the full testing period." },
    ],
  },
  {
    id: "art_0502",
    slug: "gemini-in-gmail-review",
    title: "Gemini in Gmail: Is the AI in Your Inbox Worth Using?",
    subtitle: "Google put an assistant next to your email. We tested whether it earns the space.",
    excerpt: "Summaries, suggested replies and a “help me write” button. Our reviewer spent two weeks with Gemini in Gmail to find out what is useful and what is clutter.",
    shortSummary: "Two weeks with Gemini inside Gmail.",
    category: "reviews",
    tags: ["Gemini", "Gmail", "Reviews"],
    authorSlug: "daniel-reyes",
    status: "published",
    publishedAt: "2026-09-03T10:00:00Z",
    updatedAt: "2026-09-03T10:00:00Z",
    featuredImage: featured("gemini-in-gmail", "A soft envelope-like fold rendered in navy planes with a light-blue seal."),
    keyTakeaways: ["Thread summaries are the standout feature.", "Suggested replies need editing before sending.", "You can turn it off if you prefer."],
    relatedArticles: ["the-5-ai-tools-worth-knowing-this-week", "how-ai-can-help-you-write-better-emails"],
    tools: ["gemini"],
    affiliateLinks: ["gemini-advanced"],
    content: [
      { type: "paragraph", text: "Editorial placeholder: this review structure is ready for a full hands-on report. Sections follow NUVORA's standard review format." },
      { type: "heading", level: 2, text: "The good" },
      { type: "paragraph", text: "Summaries of long threads are genuinely useful and accurate in our testing. For anyone who receives group emails, this alone justifies a look." },
      { type: "heading", level: 2, text: "The less good" },
      { type: "paragraph", text: "Suggested replies are polite but generic. Treat them as a starting point, never a finished message." },
      { type: "toolRecommendation", toolSlug: "gemini", note: "Included with many Google accounts — check before paying for anything." },
      { type: "bottomLine", text: "Verdict placeholder — the tools desk assigns a final verdict after the full testing period." },
    ],
  },
  {
    id: "art_0503",
    slug: "ai-photo-tools-on-your-phone-review",
    title: "The AI Photo Tools Already on Your Phone, Reviewed",
    subtitle: "Erase a stranger, fix the lighting, sharpen a memory. What the built-in tools can do, and where they go too far.",
    excerpt: "Most modern phones now include AI editing tools. We tested the common features across several phones so you know which are worth learning.",
    shortSummary: "The AI photo features built into modern phones, tested.",
    category: "reviews",
    tags: ["Photos", "Phones", "Reviews"],
    authorSlug: "priya-natarajan",
    status: "published",
    publishedAt: "2026-08-27T10:00:00Z",
    updatedAt: "2026-08-27T10:00:00Z",
    featuredImage: featured("phone-photo-tools", "A rounded navy rectangle in portrait orientation with a small light-blue highlight, suggesting a phone screen."),
    keyTakeaways: ["Object removal and lighting fixes are excellent.", "Generated backgrounds can look artificial.", "Learn one feature at a time."],
    relatedArticles: ["7-ways-ai-can-save-you-time-this-week"],
    content: [
      { type: "paragraph", text: "Editorial placeholder: this review structure is ready for a full hands-on report." },
      { type: "heading", level: 2, text: "Worth learning" },
      { type: "list", style: "bullet", items: ["Removing a photobomber from a family picture", "Brightening a dark restaurant photo", "Sharpening an old scanned print"] },
      { type: "heading", level: 2, text: "Approach with care" },
      { type: "list", style: "bullet", items: ["Replacing skies or backgrounds", "Adding elements that were never there"] },
      { type: "bottomLine", text: "Verdict placeholder — assigned after the full testing period." },
    ],
  },
];
