import type { Article } from "../types";
import { featured } from "./_helpers";

export const toolsArticles: Article[] = [
  {
    id: "art_0101",
    slug: "the-5-ai-tools-worth-knowing-this-week",
    title: "The 5 AI Tools Worth Knowing This Week",
    subtitle: "Hundreds of AI products launch every month. These are the five a normal person might actually use.",
    excerpt: "Our tools desk tries dozens of AI products so you do not have to. This week: five that earned a place on our list, and what each one is genuinely good for.",
    shortSummary: "Five AI tools worth a normal person's attention this week.",
    category: "tools",
    tags: ["ChatGPT", "Claude", "Gemini", "Perplexity", "Copilot"],
    authorSlug: "daniel-reyes",
    status: "published",
    publishedAt: "2026-09-16T11:00:00Z",
    updatedAt: "2026-09-16T11:00:00Z",
    featuredImage: featured("five-tools-this-week", "Five soft rectangles of varying navy tones arranged in a row on warm paper."),
    popular: true,
    trending: true,
    keyTakeaways: ["You do not need more than one assistant.", "Choose based on the apps you already use.", "Free tiers are enough for most people."],
    relatedArticles: ["claude-vs-chatgpt-what-normal-people-need-to-know", "how-to-compare-ai-tools", "perplexity-review-the-search-engine-that-answers"],
    tools: ["chatgpt", "claude", "gemini", "perplexity", "copilot"],
    affiliateLinks: ["chatgpt-plus", "claude-pro"],
    content: [
      { type: "paragraph", text: "Every week our inbox fills with launches. Most are for developers, or for companies, or are a slightly different version of something that already exists. We filter all of it through one question: would this help someone who is not a technology person? This week, five passed." },
      { type: "heading", level: 2, text: "ChatGPT — the reliable generalist" },
      { type: "paragraph", text: "Still the assistant most people start with, and for good reason. It is easy, it is everywhere, and its new suggested starting points make the first few minutes much less awkward." },
      { type: "toolRecommendation", toolSlug: "chatgpt", note: "Best if you want one tool that does a bit of everything." },
      { type: "heading", level: 2, text: "Claude — for long documents and careful writing" },
      { type: "paragraph", text: "If your work involves reports, contracts or long email threads, Claude's calm, organized answers are a pleasure to work with. It is also the assistant our editors reach for when rewriting a difficult paragraph." },
      { type: "toolRecommendation", toolSlug: "claude", note: "Best for readers, writers and anyone who deals with long documents." },
      { type: "heading", level: 2, text: "Gemini — if you live in Google" },
      { type: "paragraph", text: "Gemini's strength is location. It is inside Gmail, Docs and Android. If those are your daily tools, it is the assistant that requires the least effort to start using." },
      { type: "toolRecommendation", toolSlug: "gemini", note: "Best for Gmail and Google Docs households." },
      { type: "heading", level: 2, text: "Perplexity — search that shows its work" },
      { type: "paragraph", text: "Perplexity answers questions in full sentences with numbered sources. For researching a purchase or understanding a news story, it is faster and calmer than a page of search results." },
      { type: "toolRecommendation", toolSlug: "perplexity", note: "Best when you want answers with sources you can check." },
      { type: "heading", level: 2, text: "Microsoft Copilot — for the office" },
      { type: "paragraph", text: "If your days are spent in Outlook, Word and Excel, Copilot is already there. It is particularly good at explaining spreadsheet formulas in plain language." },
      { type: "toolRecommendation", toolSlug: "copilot", note: "Best for Microsoft 365 users." },
      { type: "bottomLine", text: "Pick the one closest to the apps you already use. You can always switch later — none of them require a commitment." },
    ],
  },
  {
    id: "art_0102",
    slug: "claude-vs-chatgpt-what-normal-people-need-to-know",
    title: "Claude vs. ChatGPT: What Normal People Actually Need to Know",
    subtitle: "Two of the best assistants, compared on the things that matter at a kitchen table — not in a laboratory.",
    excerpt: "Both are excellent. Both are free to start. The difference is mostly about tone, documents and where each one lives. Here is how to choose.",
    shortSummary: "Claude and ChatGPT compared on what matters to normal people.",
    category: "tools",
    tags: ["Claude", "ChatGPT", "Comparisons"],
    authorSlug: "daniel-reyes",
    status: "published",
    publishedAt: "2026-09-14T10:00:00Z",
    updatedAt: "2026-09-17T09:20:00Z",
    featuredImage: featured("claude-vs-chatgpt", "Two balanced navy forms facing each other across a warm paper field, divided by a thin light-blue line."),
    featured: true,
    popular: true,
    keyTakeaways: ["Both handle everyday tasks well; you will not go wrong with either.", "Claude is stronger with long documents and careful writing.", "ChatGPT has more consumer features and is more widely integrated."],
    seoTitle: "Claude vs. ChatGPT (2026): A Plain-English Comparison",
    relatedArticles: ["the-5-ai-tools-worth-knowing-this-week", "how-to-compare-ai-tools", "how-ai-can-help-you-write-better-emails"],
    tools: ["claude", "chatgpt"],
    affiliateLinks: ["chatgpt-plus", "claude-pro"],
    content: [
      { type: "paragraph", text: "Readers ask us this question more than any other. The honest answer is that for most everyday tasks — explaining a letter, planning a trip, rewriting an email — the two assistants are close enough that you would be happy with either. But they do have personalities, and those personalities suit different people." },
      { type: "heading", level: 2, text: "Where they are the same" },
      { type: "paragraph", text: "Both are free to try. Both understand plain English. Both can read a document you paste in, explain it, and answer questions about it. Both can be wrong, and both will occasionally state something incorrect with complete confidence." },
      { type: "heading", level: 2, text: "Where they differ" },
      {
        type: "table",
        table: {
          caption: "A plain-English comparison. Details are editorial placeholders pending verification.",
          columns: ["", "Claude", "ChatGPT"],
          rows: [
            ["Tone", "Calm, measured, well organized", "Friendly, conversational"],
            ["Long documents", "Excellent — handles very long files", "Good"],
            ["Where it lives", "Website, apps", "Website, apps, and inside many other products"],
            ["Voice conversation", "Available", "Available and mature"],
            ["Free tier", "Yes, with limits", "Yes, with limits"],
            ["Paid tier", "About $20 / month", "About $20 / month"],
          ],
        },
      },
      { type: "explains", term: "Why do assistants “make things up”?", text: "These tools predict likely words based on patterns in text; they do not look facts up unless connected to a search tool. When a pattern is strong but the fact is wrong, the result is a confident mistake. This is why we suggest checking anything important — a date, a dosage, a legal claim — against a reliable source." },
      { type: "heading", level: 2, text: "Who should choose Claude" },
      { type: "list", style: "bullet", items: ["You read and write long documents.", "You prefer a quieter, more careful tone.", "You want answers that are clearly structured."] },
      { type: "heading", level: 2, text: "Who should choose ChatGPT" },
      { type: "list", style: "bullet", items: ["You want one assistant with the most features.", "You like talking to it out loud.", "You use products that already include it."] },
      { type: "whyItMatters", text: "The choice is low-stakes. Both are free to try, neither locks you in, and switching takes a minute. The real decision is not which tool — it is whether you use one at all." },
      { type: "toolRecommendation", toolSlug: "claude", note: "Our pick for writing and documents." },
      { type: "toolRecommendation", toolSlug: "chatgpt", note: "Our pick for an all-round first assistant." },
      { type: "bottomLine", text: "Try both for the same task — rewriting one email — and keep the one whose answer you liked more. That is a perfectly good way to decide." },
      { type: "faq", items: [
        { question: "Can I use both?", answer: "Yes. Many of our editors do. There is no penalty for having accounts with both." },
        { question: "Is one safer than the other?", answer: "Both have similar privacy settings. Review them, and avoid pasting sensitive documents into any assistant unless you have read its data policy." },
      ] },
    ],
  },
  {
    id: "art_0103",
    slug: "how-to-compare-ai-tools",
    title: "How to Compare AI Tools Without Losing Your Mind",
    subtitle: "Ignore the benchmarks. Ask four practical questions instead.",
    excerpt: "Every AI product claims to be the best. Here is a simple, four-question method for comparing them on the things that will actually affect you.",
    shortSummary: "Four questions that make comparing AI tools simple.",
    category: "tools",
    tags: ["Comparisons", "Guides"],
    authorSlug: "daniel-reyes",
    status: "published",
    publishedAt: "2026-09-02T10:00:00Z",
    updatedAt: "2026-09-02T10:00:00Z",
    featuredImage: featured("how-to-compare-ai-tools", "Four small navy squares aligned along a light-blue baseline on paper."),
    keyTakeaways: ["Where does it live? Convenience beats capability.", "What will you use it for? Test that one task.", "What does it cost, and is the free tier enough?", "What happens to what you type?"],
    relatedArticles: ["claude-vs-chatgpt-what-normal-people-need-to-know", "the-5-ai-tools-worth-knowing-this-week", "how-to-use-ai-safely"],
    content: [
      { type: "paragraph", text: "AI companies compare their products using benchmarks — tests with names like acronyms and scores to two decimal places. Those numbers are meaningful to researchers. They are almost meaningless to you. Here is what to ask instead." },
      { type: "heading", level: 2, text: "1. Where does it live?" },
      { type: "paragraph", text: "The best tool is the one you will actually open. If it is already in your email or your phone, you will use it. If it requires a new website and a new login, you probably will not." },
      { type: "heading", level: 2, text: "2. What is the one task you want help with?" },
      { type: "paragraph", text: "Pick a real, recurring task. Give the same task to two tools. Compare the results yourself. Ten minutes of this teaches you more than any review." },
      { type: "heading", level: 2, text: "3. Is the free version enough?" },
      { type: "paragraph", text: "For most people, yes. Paid tiers add capacity and a few features; they rarely change whether the tool is useful to you." },
      { type: "heading", level: 2, text: "4. What happens to what you type?" },
      { type: "paragraph", text: "Read the privacy settings once. Most tools let you opt out of having your conversations used for training. Do that, and avoid pasting anything you would not email to a stranger." },
      { type: "bottomLine", text: "Convenience, one real task, a free tier, and a privacy check. Four questions, ten minutes, and you will know more than most reviewers." },
    ],
  },
];
