import type { Article } from "../types";
import { featured } from "./_helpers";

export const workArticles: Article[] = [
  {
    id: "art_0401",
    slug: "what-ai-means-for-your-job-a-calm-guide",
    title: "What AI Means for Your Job: A Calm Guide",
    subtitle: "Neither the doom nor the hype is accurate. Here is a grounded look at what is actually changing, profession by profession.",
    excerpt: "The honest answer is: it depends on what you do all day. We break down the tasks AI is good at, the ones it is not, and what that means for the work most Americans do.",
    shortSummary: "A calm, practical look at AI and your career.",
    category: "ai-at-work",
    tags: ["Careers", "Jobs", "Explainers"],
    authorSlug: "thomas-whitfield",
    status: "published",
    publishedAt: "2026-09-12T08:00:00Z",
    updatedAt: "2026-09-12T08:00:00Z",
    featuredImage: featured("ai-and-your-job", "An orderly grid of navy blocks with a single light-blue block shifted upward, suggesting change within structure."),
    featured: true,
    popular: true,
    keyTakeaways: ["AI changes tasks faster than it changes jobs.", "Writing, summarizing and routine analysis are most affected.", "The people benefiting most are those using AI for the tedious parts of their own work."],
    relatedArticles: ["the-quiet-way-ai-is-changing-the-office", "ai-agents-are-coming-heres-what-that-means", "how-ai-can-help-you-write-better-emails"],
    content: [
      { type: "paragraph", text: "Every few weeks a headline announces that AI will eliminate half of all jobs, or none of them. Neither is a serious claim. The useful way to think about this is not jobs but tasks — the individual things you do between nine and five." },
      { type: "heading", level: 2, text: "Tasks AI is genuinely good at" },
      { type: "list", style: "bullet", items: ["First drafts of routine writing", "Summarizing long documents and meetings", "Sorting, categorizing and finding patterns in text", "Explaining unfamiliar material quickly"] },
      { type: "heading", level: 2, text: "Tasks it is not good at" },
      { type: "list", style: "bullet", items: ["Anything requiring physical presence", "Judgment calls with real consequences", "Relationships, trust and persuasion", "Knowing what matters in your specific workplace"] },
      { type: "whyItMatters", text: "If most of your day is on the first list, your work will change noticeably. If most is on the second, AI will be a tool you use rather than a threat you face. Most jobs are a mix — which is why most jobs will change without disappearing." },
      { type: "quote", text: "The employees who are thriving are not the ones who resisted or the ones who panicked. They are the ones who quietly handed the boring parts to an assistant.", cite: "Thomas Whitfield, Work & Careers Editor" },
      { type: "bottomLine", text: "Make a list of your own weekly tasks. Mark the ones an assistant could draft or summarize. Start there, on your own terms, before someone else decides for you." },
    ],
  },
  {
    id: "art_0402",
    slug: "the-quiet-way-ai-is-changing-the-office",
    title: "The Quiet Way AI Is Changing the Office",
    subtitle: "No robots, no layoffs — just meetings that end with a summary and emails that write themselves.",
    excerpt: "The real change in most workplaces is undramatic. We spent a month watching how ordinary offices are using AI, and found habits worth copying.",
    shortSummary: "How real offices are actually using AI day to day.",
    category: "ai-at-work",
    tags: ["Office", "Meetings", "Productivity"],
    authorSlug: "thomas-whitfield",
    status: "published",
    publishedAt: "2026-09-06T08:00:00Z",
    updatedAt: "2026-09-06T08:00:00Z",
    featuredImage: featured("quiet-office-change", "A row of soft, evenly spaced navy panels on warm paper, one slightly lighter, like windows in an office at dusk."),
    keyTakeaways: ["Meeting notes and summaries are the most common use.", "Nobody is required to use AI; the useful habits spread on their own.", "The best teams set simple rules about what not to paste in."],
    relatedArticles: ["what-ai-means-for-your-job-a-calm-guide", "how-ai-can-help-you-write-better-emails"],
    tools: ["copilot", "gemini"],
    content: [
      { type: "paragraph", text: "We asked readers in a dozen industries to describe how AI actually shows up in their workday. The answers were remarkably consistent, and remarkably undramatic." },
      { type: "heading", level: 2, text: "Meetings that end with a summary" },
      { type: "paragraph", text: "The single most common use is a meeting assistant that transcribes the call and produces a summary with action items. People who were sceptical say it is the feature they would miss most." },
      { type: "heading", level: 2, text: "Email that arrives half-written" },
      { type: "paragraph", text: "Suggested replies and thread summaries in Outlook and Gmail are now routine. Most people edit the suggestions heavily. Almost nobody sends them unchanged." },
      { type: "heading", level: 2, text: "Simple rules, not policies" },
      { type: "paragraph", text: "The teams that use AI most comfortably have one or two plain rules: no customer data in public tools, and a human reads everything before it goes out. Long policy documents, by contrast, tend to be ignored." },
      { type: "toolRecommendation", toolSlug: "copilot", note: "The most common assistant in the offices we heard from, mostly because it is already in Outlook and Teams." },
      { type: "bottomLine", text: "The office is not being transformed. It is being tidied. Summaries, drafts and fewer blank pages — that is the real story." },
    ],
  },
];
