/**
 * Self-hosts the brand typefaces.
 * Pulls the woff2 files Google Fonts would serve and writes a local @font-face
 * sheet, so the site makes no third-party request for its type: one less
 * connection on first paint, and no dependency on an external host.
 *
 *   npm run fonts
 *
 * Two things are trimmed on the way through, because Google's stylesheet is
 * built for the general case and this site is Hebrew:
 *
 *  - Only the `hebrew` and `latin` subsets are kept. Cyrillic, Greek,
 *    Vietnamese and latin-ext are never reached by this content.
 *  - Asking for several static weights makes Google repeat the whole subset
 *    set once per weight, all pointing at the same files. Those duplicates are
 *    dropped, so each file is fetched and embedded exactly once.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = resolve(root, 'public/fonts')
const sheet = resolve(root, 'src/styles/fonts.css')

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Frank+Ruhl+Libre:wght@300..900' +
  '&family=Assistant:wght@200..800' +
  '&family=Cormorant+Garamond:wght@400;500&display=swap'

/** Everything this site's content can actually reach. */
const KEEP_SUBSETS = new Set(['hebrew', 'latin'])

// A modern UA is required for Google to serve woff2 + variable fonts.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'

await mkdir(outDir, { recursive: true })

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text()

// Google emits `/* subset */` immediately before each @font-face block.
const blocks = [...css.matchAll(/\/\* ([\w-]+) \*\/\s*(@font-face \{[^}]*\})/g)]
if (blocks.length === 0) throw new Error('Could not parse the Google Fonts stylesheet')

const seen = new Set()
const kept = []
let dropped = 0

for (const [, subset, block] of blocks) {
  const url = block.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/)?.[1]
  if (!url) continue
  if (!KEEP_SUBSETS.has(subset)) { dropped += 1; continue }
  const family = block.match(/font-family: '([^']+)'/)?.[1] ?? ''
  const id = `${family}|${subset}|${url}`
  if (seen.has(id)) { dropped += 1; continue }
  seen.add(id)
  kept.push({ subset, block, url, family })
}

const nameFor = (u) => u.split('/').slice(-3).join('-').replace(/[^\w.-]/g, '_')

let out = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. Re-run: npm run fonts */\n`
let bytes = 0
for (const { subset, block, url, family } of kept) {
  const file = nameFor(url)
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`${url} → HTTP ${res.status}`)
  const buf = Buffer.from(await res.arrayBuffer())
  await writeFile(resolve(outDir, file), buf)
  bytes += buf.byteLength
  console.log(`· ${family} ${subset} — ${(buf.byteLength / 1024).toFixed(0)} KB`)
  out += `/* ${subset} */\n${block.replace(url, `/fonts/${file}`)}\n`
}

await writeFile(sheet, out, 'utf8')

// Keep index.html's preloads pointing at the files that were just written —
// the hashed names change whenever Google reissues a face.
const indexPath = resolve(root, 'index.html')
let indexHtml = await readFile(indexPath, 'utf8')
const preloads = kept
  .filter((k) => k.subset === 'hebrew')
  .map((k) => `    <link rel="preload" as="font" type="font/woff2" href="/fonts/${nameFor(k.url)}" crossorigin />`)
  .join('\n')
indexHtml = indexHtml.replace(
  /(?: *<link rel="preload" as="font"[^>]*>\n)+/,
  () => `${preloads}\n`,
)
await writeFile(indexPath, indexHtml, 'utf8')
console.log(`· index.html preloads updated (${kept.filter((k) => k.subset === 'hebrew').length} Hebrew faces)`)

console.log(
  `\n✔ ${kept.length} faces self-hosted (${(bytes / 1024).toFixed(0)} KB), ` +
    `${dropped} unused or duplicate faces dropped.`,
)
