/**
 * Self-hosts the brand typefaces.
 * Pulls the woff2 files Google Fonts would serve and writes a local @font-face
 * sheet, so the site makes no third-party request for its type: one less
 * connection on first paint, and no dependency on an external host.
 *
 *   npm run fonts
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = resolve(root, 'public/fonts')
const sheet = resolve(root, 'src/styles/fonts.css')

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Frank+Ruhl+Libre:wght@300..900&family=Assistant:wght@200..800&family=Cormorant+Garamond:wght@300;400;500;600&display=swap'

// A modern UA is required for Google to serve woff2 + variable fonts.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'

await mkdir(outDir, { recursive: true })

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text()

const urls = [...new Set([...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g)].map((m) => m[1]))]
if (urls.length === 0) throw new Error('No font files found in the Google Fonts response')

const nameFor = (u) => u.split('/').slice(-3).join('-').replace(/[^\w.-]/g, '_')

let local = css
for (const u of urls) {
  const file = nameFor(u)
  const res = await fetch(u, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`${u} → HTTP ${res.status}`)
  await writeFile(resolve(outDir, file), Buffer.from(await res.arrayBuffer()))
  local = local.split(u).join(`/fonts/${file}`)
  console.log(`· ${file} (${(res.headers.get('content-length') ?? 0) / 1} bytes)`)
}

await writeFile(
  sheet,
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. Re-run: npm run fonts */\n${local}`,
  'utf8',
)
console.log(`\n✔ ${urls.length} font files self-hosted; sheet written to src/styles/fonts.css`)
