import fs from "node:fs";
import path from "node:path";
import type { ComponentName } from "../../../core/types";
import type { EngineInput, EngineResult, WebsiteEngine } from "../types";
import { buildSiteContent } from "./content";
import { renderPlaceholderSvg } from "./placeholder";
import { renderTokensCss } from "./tokens";

/** Resolved from the studio root (npm scripts and `next start` both run there). Override with STUDIO_ROOT. */
const templateDir = () => path.resolve(process.env.STUDIO_ROOT ?? process.cwd(), "templates", "nextjs-site");

const TYPE_EXPORT: Partial<Record<ComponentName, string>> = {
  Navbar: "NavbarProps", Hero: "HeroProps", VideoHero: "VideoHeroProps", Marquee: "MarqueeProps", SplitSection: "SplitSectionProps",
  Services: "ServicesProps", ScrollStory: "ScrollStoryProps", BeforeAfter: "BeforeAfterProps", ImageGallery: "ImageGalleryProps",
  Process: "ProcessProps", Trust: "TrustProps", Testimonials: "TestimonialsProps", FAQ: "FAQProps", CTA: "CTAProps",
  Contact: "ContactProps", Footer: "FooterProps", Stats: "StatsProps", InteractiveCards: "InteractiveCardsProps",
};

function copyDir(src: string, dest: string, out: string[], root = dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const e of fs.readdirSync(src, { withFileTypes: true })) {
    if (e.name === "node_modules" || e.name === ".next") continue;
    const s = path.join(src, e.name), d = path.join(dest, e.name);
    if (e.isDirectory()) copyDir(s, d, out, root);
    else { fs.copyFileSync(s, d); out.push(path.relative(root, d)); }
  }
}

function renderPage(sections: { id: string; component: ComponentName }[]): string {
  const used = [...new Set(sections.map((s) => s.component))];
  const imports = used.map((c) => `import { ${c}${TYPE_EXPORT[c] ? `, type ${TYPE_EXPORT[c]}` : ""} } from "../components/${c}";`).join("\n");
  const jsx = (s: { id: string; component: ComponentName }) => `<${s.component} {...sec<${TYPE_EXPORT[s.component] ?? "Record<string, unknown>"}>("${s.id}")} />`;
  const nav = sections.filter((s) => s.component === "Navbar");
  const foot = sections.filter((s) => s.component === "Footer");
  const body = sections.filter((s) => s.component !== "Navbar" && s.component !== "Footer");
  return `// GENERATED by DynaTech AI Studio (Next.js engine). Content lives in content/site.json; styles in app/tokens.css.
import { sec } from "../lib/site";
${imports}

export default function Page() {
  return (
    <>
      <a className="skip-link" href="#main">Skip to content</a>
      <div id="top" />
      ${nav.map(jsx).join("\n      ")}
      <main id="main">
        ${body.map(jsx).join("\n        ")}
      </main>
      ${foot.map(jsx).join("\n      ")}
    </>
  );
}
`;
}

export class NextJsEngine implements WebsiteEngine {
  readonly id = "nextjs";
  readonly label = "Next.js + React + TypeScript";
  readonly status = "ready" as const;

  async generate({ memory, outputDir }: EngineInput): Promise<EngineResult> {
    const files: string[] = [];
    // Regenerable directories are replaced wholesale so revisions never leave stale files behind.
    for (const d of ["app", "components", "lib", "content", path.join("public", "media")]) fs.rmSync(path.join(outputDir, d), { recursive: true, force: true });
    const tpl = templateDir();
    if (!fs.existsSync(tpl)) throw new Error(`Site template not found at ${tpl}. Run from the studio root or set STUDIO_ROOT.`);
    copyDir(tpl, outputDir, files);

    const pkgPath = path.join(outputDir, "package.json");
    const slug = memory.copy.brandName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "site";
    fs.writeFileSync(pkgPath, fs.readFileSync(pkgPath, "utf8").replace("__SITE_NAME__", slug));

    const { content, warnings } = buildSiteContent(memory);
    const write = (rel: string, data: string) => {
      const full = path.join(outputDir, rel);
      fs.mkdirSync(path.dirname(full), { recursive: true });
      fs.writeFileSync(full, data);
      if (!files.includes(rel)) files.push(rel);
    };
    write("content/site.json", JSON.stringify(content, null, 2));
    write("design-system.json", JSON.stringify(memory["design-system"], null, 2));
    write("app/tokens.css", renderTokensCss(memory["design-system"]));
    write("app/page.tsx", renderPage(content.sections as { id: string; component: ComponentName }[]));

    for (const a of memory.media.assets) {
      if (a.source === "placeholder" && a.url.startsWith("/media/")) {
        const portrait = (a.height ?? 0) > (a.width ?? 0);
        write(`public${a.url}`, renderPlaceholderSvg(a.slot, memory.creative.palette, portrait ? { w: 1000, h: 1250 } : { w: 1600, h: 1000 }));
      }
    }
    write("README.md", `# ${memory.copy.brandName}\n\nGenerated by DynaTech AI Studio.\n\n\`\`\`bash\nnpm install\nnpm run dev      # http://localhost:3000\nnpm run build && npm start\n\`\`\`\n\n- Content: \`content/site.json\`\n- Design tokens: \`design-system.json\` → \`app/tokens.css\`\n- Environment: copy \`.env.example\` to \`.env.local\` (set \`LEAD_WEBHOOK_URL\` to receive inquiries)\n${warnings.length ? `\n## Engine warnings\n${warnings.map((w) => `- ${w}`).join("\n")}\n` : ""}`);

    return { files: files.sort(), installCommand: "npm install", runCommand: "npm run dev", buildCommand: "npm run build" };
  }
}
