/* Generated by scripts/pexels.mjs — do not edit by hand. Re-run: npm run pexels:fetch */

export type PexelsAsset = {
  type: 'photo' | 'video'
  pexelsId: number
  src: string
  poster?: string | null
  ratio: string
  tint: string
  alt: string
  photographer: string
  pexelsUrl: string
}

/**
 * Chapter id → the Pexels asset in use.
 *
 * EMPTY. No Pexels asset has been retrieved: this environment's network policy
 * blocks api.pexels.com, images.pexels.com and www.pexels.com (403 on CONNECT),
 * so the API cannot be reached from here with or without a key.
 *
 * Run `npm run pexels:search` then `npm run pexels:fetch` on a machine with
 * network access and a PEXELS_API_KEY, and this file fills itself in. The
 * scroll experience reads it automatically and the footer starts crediting
 * the photographers.
 */
export const pexelsAssets: Record<string, PexelsAsset> = {}
