import type { IndustryProfile } from "./types";

export const landscaping: IndustryProfile = {
  key: "landscaping",
  label: "Luxury landscape design & construction",
  matches: /landscap|garden|outdoor (living|design)|hardscap|lawn|pool (design|builder)/i,
  offering: "outdoor spaces",
  customer: "homeowner",
  customerProblems: [
    "A large property that feels unfinished, unused, or disconnected from the house",
    "Fear of a multi-vendor project: designer, builder, irrigation and lighting who don't coordinate",
    "Unclear budgets and timelines on high-investment outdoor work",
    "Difficulty picturing the finished result before committing",
    "Climate realities (heat, storms, salt air, drainage) that ruin poorly planned plantings and materials",
    "Not knowing how to tell a true design-build firm from a crew that mows and plants",
  ],
  services: [
    { title: "Landscape Design", body: "Master plans that respond to your architecture, your climate and the way you actually live outdoors.", detail: "Concept sketches, plant palettes, material selections and 3D previews before ground is broken." },
    { title: "Outdoor Living & Hardscape", body: "Terraces, outdoor kitchens, fire features and pool surrounds built in natural stone and durable materials.", detail: "Structural and drainage planning is part of the design, not an afterthought." },
    { title: "Planting & Tropical Gardens", body: "Layered, climate-appropriate planting that looks composed on day one and matures gracefully.", detail: "Specimen trees, palms and understory selected for salt, sun, wind and irrigation reality." },
    { title: "Landscape Lighting", body: "Architectural lighting that reshapes the property after dark: paths, trees, water and facades.", detail: "Layered, low-glare schemes designed on site at night." },
    { title: "Irrigation & Drainage", body: "Smart irrigation and drainage engineered for heavy rain and hot, dry stretches.", detail: "Zoned by plant type, with controls you can manage from your phone." },
    { title: "Estate Care & Maintenance", body: "Ongoing care that protects the investment: pruning, seasonal color, lighting and irrigation checks.", detail: "Scheduled visits and clear reporting." },
  ],
  positioning: [
    "Design-build: one accountable team from concept to final lighting",
    "Architectural approach: landscapes treated as an extension of the home",
    "Visualize-first process: clients approve a clear plan before construction",
    "Regionally intelligent plant and material choices",
  ],
  websitePatterns: [
    "Full-bleed cinematic hero with a single confident headline",
    "Scroll-driven before/after or stage-by-stage transformation storytelling",
    "Large, uncropped project photography with minimal captions",
    "Consultation-first CTA repeated at natural decision points",
    "Process section to reduce fear of large projects",
    "Trust built through credentials and references, not badges and stars",
  ],
  recommendations: [
    "Lead with the transformation story: the site's core promise is 'from empty land to a finished garden'.",
    "Use dusk and golden-hour photography; lighting sells luxury outdoors.",
    "Make the private consultation the single primary conversion action.",
    "Show the process early: high-value buyers want certainty before inspiration.",
    "Reserve real credentials (licenses, insurance, references) for the trust section; never fabricate them.",
  ],
  primaryCta: "Request a Private Consultation",
  secondaryCta: "See the Transformation",
  heroHeadlines: ["Landscapes designed to be lived in.", "Where your property becomes a destination.", "The outdoors, finished properly."],
  heroSub: "Design-build landscape architecture for {audience} in {city}: gardens, terraces, pools and lighting, planned and built as one.",
  introHeadline: "One vision. One accountable team. From bare ground to finished garden.",
  introBody: [
    "A property of this caliber deserves more than a planting plan. It deserves a coordinated design that respects the architecture, the climate and the way you live.",
    "We work from concept to final lighting so the design you approve is the landscape you get.",
  ],
  transformation: true,
  storyTitle: "The transformation, stage by stage",
  storyIntro: "Every landscape follows the same arc. Scroll through it: raw ground becomes a considered, finished place.",
  stages: [
    { label: "The blank canvas", caption: "Open ground, existing trees, sun paths and drainage. We read the site before we draw a line." },
    { label: "Design", caption: "Master plan, plant palette and materials: a clear vision you approve before anything is built." },
    { label: "Construction", caption: "Grading, drainage, stonework and structures built to last." },
    { label: "Planting", caption: "Specimen trees and layered planting install the soul of the garden." },
    { label: "Lighting", caption: "Architectural lighting is tuned on site, after dark." },
    { label: "The finished garden", caption: "A place that looks resolved on day one and grows better each season." },
  ],
  beforeAfter: {
    headline: "See the difference design makes",
    body: "Drag the handle to compare the same view before and after.",
    before: "Before", after: "After",
  },
  process: {
    headline: "A process built for large investments",
    intro: "Clarity at each step, so nothing about your project is a surprise.",
    steps: [
      { title: "Private consultation", body: "We walk the property with you, listen, and discuss goals, budget range and timeline." },
      { title: "Concept & master plan", body: "Sketches, materials, plant palette and 3D visuals so you can see the outcome first." },
      { title: "Proposal & scope", body: "A written scope and budget so you can decide with confidence." },
      { title: "Build", body: "Coordinated construction, planting, irrigation and lighting under one team." },
      { title: "Handover & care", body: "A final walkthrough, care guidance and optional ongoing maintenance." },
    ],
  },
  trust: {
    headline: "How to choose a landscape partner",
    intro: "Four things worth verifying with any firm you consider, including us.",
    checklist: [
      { title: "Current licensing", body: "Ask for license numbers and verify them with the state licensing board." },
      { title: "Insurance coverage", body: "Request proof of liability and workers' compensation coverage." },
      { title: "Recent references", body: "Speak with clients whose projects match yours in scale and complexity." },
      { title: "A written scope", body: "Insist on drawings, a defined scope and a payment schedule before work starts." },
    ],
    proofSlots: [
      { label: "License number", hint: "Add your state contractor / landscape license number" },
      { label: "Insurance", hint: "Add coverage statement or certificate link" },
      { label: "Awards & memberships", hint: "Add real industry memberships or awards, if any" },
      { label: "Review rating", hint: "Add your verified Google rating and count" },
    ],
  },
  faq: [
    { q: "How long does a landscape project take?", a: "It depends on scope, permitting and materials. After the consultation you'll receive a written timeline with the proposal." },
    { q: "Do you handle permits and approvals?", a: "Large outdoor projects often require permits or HOA approval. We'll outline what your project needs during planning." },
    { q: "Can I see the design before construction begins?", a: "Yes. The design phase produces a master plan and visuals so you know what you're approving." },
    { q: "How is a project priced?", a: "Every property is different. We provide a written scope and budget after the consultation and design phase." },
    { q: "Do you offer maintenance after installation?", a: "Ongoing care is available so the landscape matures the way it was designed." },
  ],
  marquee: ["Landscape design", "Outdoor living", "Hardscape", "Tropical planting", "Landscape lighting", "Irrigation", "Estate care"],
  formOptions: { label: "Project type", options: ["Full landscape redesign", "Outdoor living / pool area", "Planting & gardens", "Lighting", "Not sure yet"] },
  schemaType: "HomeAndConstructionBusiness",
  galleryCaptions: ["Terrace at dusk", "Tropical planting", "Pool surround", "Architectural lighting", "Garden path", "Outdoor living"],
  media: {
    hero: "luxury modern backyard landscaping {city} sunset",
    video: "luxury backyard garden landscape pool aerial cinematic golden hour",
    story: [
      "empty green lot land open field",
      "landscape architect blueprint garden plan drawing",
      "landscape construction stone patio installation",
      "tropical planting palm trees garden installation",
      "landscape lighting garden night illuminated",
      "luxury garden pool finished backyard twilight",
    ],
    gallery: [
      "luxury backyard terrace dusk modern architecture",
      "tropical garden lush palms modern villa",
      "luxury swimming pool surround stone landscaping",
      "landscape lighting trees night garden",
      "garden path stone walkway manicured",
      "outdoor living kitchen patio luxury",
    ],
    split: "modern luxury home exterior manicured garden",
    contact: "luxury home backyard evening lights",
    beforeAfter: ["bare backyard dirt yard unfinished", "luxury backyard landscaped pool garden"],
    subject: "luxury residential landscapes",
  },
};
