import type { IndustryProfile } from "./types";

const noTransform = {
  transformation: false,
  storyTitle: "",
  storyIntro: "",
  stages: [] as { label: string; caption: string }[],
  beforeAfter: { headline: "", body: "", before: "", after: "" },
};

export const restaurant: IndustryProfile = {
  key: "restaurant",
  label: "Fine dining & hospitality",
  matches: /restaurant|bistro|steakhouse|cafe|café|bar & grill|eatery|dining|chef/i,
  offering: "dining experiences",
  customer: "guest",
  customerProblems: [
    "Hard to judge atmosphere and quality from generic photos",
    "Unclear menus, hours and reservation paths on mobile",
    "Uncertainty about whether a venue fits a special occasion or a group",
  ],
  services: [
    { title: "Dinner", body: "The main experience: a menu shaped around seasonal ingredients.", detail: "[Add your dinner menu highlights]" },
    { title: "Private Dining", body: "Spaces and menus for celebrations and corporate gatherings.", detail: "[Add capacity and minimums]" },
    { title: "Bar & Cocktails", body: "A bar program designed to be part of the evening, not a waiting room.", detail: "[Add signature drinks]" },
    { title: "Events & Catering", body: "Bring the kitchen to your event, or the event to the room.", detail: "[Add catering details]" },
  ],
  positioning: ["Atmosphere-led", "Ingredient and chef-driven story", "Effortless reservations"],
  websitePatterns: ["Full-bleed food and room photography", "Sticky reservation button", "Menu as readable text, not a PDF", "Hours, address and map above the fold on mobile"],
  recommendations: ["Show the room, the food and the people in the first three screens.", "Make reservations reachable in one tap on mobile.", "Publish menus as real HTML text for SEO and accessibility."],
  primaryCta: "Reserve a Table",
  secondaryCta: "View the Menu",
  heroHeadlines: ["An evening worth planning around.", "Dinner, done with intent."],
  heroSub: "A {city} dining room built around seasonal ingredients and considered service.",
  introHeadline: "The room, the kitchen, the evening.",
  introBody: ["Great dining is a sum of small decisions: the light, the pacing, the plate.", "[Add your story: chef, sourcing, philosophy]"],
  ...noTransform,
  process: { headline: "Your evening, step by step", intro: "From booking to the last course.", steps: [
    { title: "Reserve", body: "Choose your date and party size." },
    { title: "Arrive", body: "Be welcomed and seated." },
    { title: "Dine", body: "Enjoy the menu at your own pace." },
    { title: "Return", body: "Celebrate again, or book a private event." },
  ] },
  trust: { headline: "Before you book", intro: "The details guests ask about most.", checklist: [
    { title: "Dietary needs", body: "Tell us about allergies when booking so the kitchen can plan." },
    { title: "Groups & events", body: "Parties above a certain size may need a private-dining inquiry." },
    { title: "Hours & location", body: "Check current hours and directions before you arrive." },
    { title: "Cancellation", body: "Review the reservation policy at booking." },
  ], proofSlots: [
    { label: "Press & awards", hint: "Add real press mentions or awards" },
    { label: "Review rating", hint: "Add verified rating and count" },
  ] },
  faq: [
    { q: "Do you accommodate dietary restrictions?", a: "Please tell us when you reserve so the kitchen can prepare." },
    { q: "Can I host a private event?", a: "Send an inquiry with date, guest count and occasion, and we'll reply with options." },
    { q: "Where can I park?", a: "[Add parking information]" },
  ],
  marquee: ["Seasonal menu", "Private dining", "Cocktails", "Events"],
  formOptions: { label: "Inquiry type", options: ["Reservation", "Private dining", "Catering", "Other"] },
  schemaType: "Restaurant",
  galleryCaptions: ["The dining room", "Signature plate", "The bar", "Kitchen", "Private room", "Dessert"],
  media: {
    hero: "fine dining restaurant interior evening warm light {city}",
    video: "restaurant kitchen chef plating fine dining cinematic",
    story: [], gallery: [
      "fine dining plated dish chef", "restaurant interior elegant table setting", "cocktail bar bartender pouring",
      "chef kitchen cooking flame", "private dining room elegant", "dessert plating fine dining",
    ], split: "restaurant table candlelight dinner", contact: "restaurant exterior evening", beforeAfter: ["", ""],
    subject: "fine dining food and interiors",
  },
};

export const lawFirm: IndustryProfile = {
  key: "law",
  label: "Legal & professional services",
  matches: /law|attorney|lawyer|legal|solicitor|advocate/i,
  offering: "legal representation",
  customer: "client",
  customerProblems: [
    "Unsure whether a lawyer is right for their specific issue",
    "Anxiety about cost, timeline and outcome",
    "Difficulty judging credibility from marketing language",
  ],
  services: [
    { title: "[Practice area 1]", body: "Describe who you help and the outcome you work toward.", detail: "[Add scope]" },
    { title: "[Practice area 2]", body: "Describe who you help and the outcome you work toward.", detail: "[Add scope]" },
    { title: "[Practice area 3]", body: "Describe who you help and the outcome you work toward.", detail: "[Add scope]" },
  ],
  positioning: ["Clarity over jargon", "Responsive, senior-level attention", "Measured, credible tone"],
  websitePatterns: ["Restrained typography, generous white space", "Attorney profiles with real credentials", "Practice-area pages", "Confidential contact form"],
  recommendations: ["Use real attorney photos and bar admissions only.", "Explain what happens after someone reaches out.", "Keep tone measured; avoid guarantees of outcomes."],
  primaryCta: "Request a Confidential Consultation",
  secondaryCta: "View Practice Areas",
  heroHeadlines: ["Clear counsel when it matters most.", "Serious matters, plainly explained."],
  heroSub: "Legal representation for {audience} in {city}, with direct communication from first call to resolution.",
  introHeadline: "Experienced judgment, without the runaround.",
  introBody: ["[Add your firm's approach and what clients can expect]"],
  ...noTransform,
  process: { headline: "What happens after you reach out", intro: "A predictable path from first contact to resolution.", steps: [
    { title: "Confidential inquiry", body: "Tell us the basics through the form or by phone." },
    { title: "Initial consultation", body: "We assess the matter and explain options." },
    { title: "Engagement", body: "A written agreement covers scope and fees." },
    { title: "Representation", body: "We keep you informed at each stage." },
  ] },
  trust: { headline: "Verify before you hire", intro: "What to check with any attorney.", checklist: [
    { title: "Bar admission", body: "Confirm active status with the state bar." },
    { title: "Relevant experience", body: "Ask about matters similar to yours." },
    { title: "Fee clarity", body: "Get fee structure in writing." },
    { title: "Communication", body: "Ask how and how often you'll be updated." },
  ], proofSlots: [
    { label: "Bar admissions", hint: "Add real admissions and bar numbers" },
    { label: "Recognition", hint: "Add real recognitions" },
  ] },
  faq: [
    { q: "Is my inquiry confidential?", a: "Information you submit is used to evaluate your matter. [Confirm with your firm's confidentiality policy]" },
    { q: "How are fees structured?", a: "[Add fee structures offered]" },
  ],
  marquee: ["Counsel", "Litigation", "Advisory", "Representation"],
  formOptions: { label: "Matter type", options: ["Consultation", "Other"] },
  schemaType: "LegalService",
  galleryCaptions: [],
  media: { hero: "law office modern city skyline professional {city}", video: "", story: [], gallery: [], split: "attorney meeting client office", contact: "law office interior", beforeAfter: ["", ""], subject: "professional office settings" },
};

export const dental: IndustryProfile = {
  key: "dental",
  label: "Dental & clinic care",
  matches: /dental|dentist|orthodont|clinic|medical|dermatolog|therapy|wellness/i,
  offering: "clinical care",
  customer: "patient",
  customerProblems: [
    "Anxiety about treatment, cost and discomfort",
    "Difficulty judging clinical quality from marketing",
    "Wanting a clear path to book quickly",
  ],
  services: [
    { title: "[Treatment 1]", body: "Explain what it is and who it's for.", detail: "[Add details]" },
    { title: "[Treatment 2]", body: "Explain what it is and who it's for.", detail: "[Add details]" },
    { title: "[Treatment 3]", body: "Explain what it is and who it's for.", detail: "[Add details]" },
  ],
  positioning: ["Calm, transparent care", "Clear pricing conversations", "Modern equipment and comfort"],
  websitePatterns: ["Calm imagery and clean layouts", "Online booking CTA", "Clinician profiles", "FAQ addressing anxiety and cost"],
  recommendations: ["Use real staff and clinic photos.", "Avoid outcome guarantees.", "Make booking one tap on mobile."],
  primaryCta: "Book an Appointment",
  secondaryCta: "Explore Treatments",
  heroHeadlines: ["Care that starts with a conversation.", "Comfortable, clear, considered care."],
  heroSub: "Modern care for {audience} in {city}, explained clearly and delivered calmly.",
  introHeadline: "Your comfort shapes every visit.",
  introBody: ["[Add your practice philosophy and clinicians]"],
  ...noTransform,
  process: { headline: "Your first visit", intro: "What to expect.", steps: [
    { title: "Book", body: "Choose a time that suits you." },
    { title: "Consultation", body: "We listen, examine and discuss options." },
    { title: "Plan", body: "A clear plan and cost estimate." },
    { title: "Care", body: "Treatment with your comfort in mind." },
  ] },
  trust: { headline: "Before you choose a clinic", intro: "What to verify with any provider.", checklist: [
    { title: "Licensure", body: "Confirm clinicians are licensed." },
    { title: "Clear estimates", body: "Ask for costs in writing." },
    { title: "Sterilization standards", body: "Ask how instruments are sterilized." },
    { title: "Follow-up care", body: "Ask what happens if you have concerns later." },
  ], proofSlots: [
    { label: "Licenses & credentials", hint: "Add real credentials" },
    { label: "Reviews", hint: "Add verified rating" },
  ] },
  faq: [
    { q: "Do you offer payment plans?", a: "[Add your financing options]" },
    { q: "What if I feel anxious?", a: "Tell us at booking; we'll plan your visit around your comfort." },
  ],
  marquee: ["Consultations", "Treatment", "Preventive care", "Follow-up"],
  formOptions: { label: "Reason for visit", options: ["New patient consultation", "Follow-up", "Other"] },
  schemaType: "MedicalBusiness",
  galleryCaptions: [],
  media: { hero: "modern dental clinic interior bright calm {city}", video: "", story: [], gallery: [], split: "dentist patient consultation friendly", contact: "clinic reception modern", beforeAfter: ["", ""], subject: "modern clinic interiors" },
};

/** Fallback for any industry the knowledge base doesn't specialise in. An LLM provider tailors this fully. */
export const generic: IndustryProfile = {
  key: "generic",
  label: "Professional services",
  matches: /.*/,
  offering: "services",
  customer: "customer",
  customerProblems: [
    "Difficulty judging quality and credibility before contacting a business",
    "Unclear next step and what working together involves",
    "Uncertainty about cost and timeline",
  ],
  services: [
    { title: "[Service 1]", body: "Describe the outcome this service delivers.", detail: "[Add details]" },
    { title: "[Service 2]", body: "Describe the outcome this service delivers.", detail: "[Add details]" },
    { title: "[Service 3]", body: "Describe the outcome this service delivers.", detail: "[Add details]" },
  ],
  positioning: ["Clear expertise", "Transparent process", "Responsive communication"],
  websitePatterns: ["Strong hero with a single primary CTA", "Services overview", "Process section", "Trust section built from verifiable proof", "Contact form"],
  recommendations: ["Add real credentials and reviews in the trust section.", "Keep one primary CTA across the site.", "Configure an LLM provider to tailor research and copy to this specific industry."],
  primaryCta: "Get in Touch",
  secondaryCta: "See How It Works",
  heroHeadlines: ["Work that speaks for itself.", "Done properly, from the first conversation."],
  heroSub: "{offeringTitle} for {audience} in {city}.",
  introHeadline: "A clear process and a team you can reach.",
  introBody: ["[Add your story and what makes your approach different]"],
  ...noTransform,
  process: { headline: "How we work together", intro: "A simple, predictable path.", steps: [
    { title: "Reach out", body: "Tell us what you need." },
    { title: "Discovery", body: "We learn your goals and constraints." },
    { title: "Proposal", body: "You receive a clear scope." },
    { title: "Delivery", body: "We deliver and keep you informed." },
  ] },
  trust: { headline: "What to verify before you hire", intro: "Good questions for any provider.", checklist: [
    { title: "Credentials", body: "Ask for relevant licenses or certifications." },
    { title: "References", body: "Speak with clients with similar needs." },
    { title: "Written scope", body: "Get scope and pricing in writing." },
    { title: "Communication", body: "Agree how you'll stay in touch." },
  ], proofSlots: [
    { label: "Credentials", hint: "Add real credentials" },
    { label: "Reviews", hint: "Add verified reviews" },
  ] },
  faq: [
    { q: "How do we get started?", a: "Send an inquiry with the form. We'll reply with next steps." },
    { q: "How is pricing determined?", a: "[Add how you price]" },
  ],
  marquee: ["Consultation", "Planning", "Delivery", "Support"],
  formOptions: { label: "How can we help?", options: ["General inquiry", "Request a quote", "Other"] },
  schemaType: "LocalBusiness",
  galleryCaptions: [],
  media: { hero: "professional team modern office {city}", video: "", story: [], gallery: [], split: "professional consultation meeting", contact: "modern office interior", beforeAfter: ["", ""], subject: "professional services" },
};
